"""index run_id on raw_monthly_reports and quarantined_reports

Revision ID: cd260a0569e1
Revises: feec6204d742
Create Date: 2026-07-21 22:36:56.733830

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'cd260a0569e1'
down_revision: Union[str, Sequence[str], None] = 'feec6204d742'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_quarantined_reports_run_id'), 'quarantined_reports', ['run_id'], unique=False)
    op.create_index(op.f('ix_raw_monthly_reports_run_id'), 'raw_monthly_reports', ['run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_raw_monthly_reports_run_id'), table_name='raw_monthly_reports')
    op.drop_index(op.f('ix_quarantined_reports_run_id'), table_name='quarantined_reports')
    # ### end Alembic commands ###
