"""initial schema

Revision ID: feec6204d742
Revises: 
Create Date: 2026-07-20 20:01:31.597155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'feec6204d742'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('facilities',
    sa.Column('facility_id', sa.String(), nullable=False),
    sa.Column('facility_name', sa.String(), nullable=False),
    sa.Column('region', sa.String(), nullable=False),
    sa.Column('ownership_type', sa.String(), nullable=False),
    sa.Column('baseline_patient_volume', sa.Integer(), nullable=False),
    sa.Column('opened_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('facility_id')
    )
    op.create_table('quarantined_reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('facility_id', sa.String(), nullable=False),
    sa.Column('report_month', sa.Date(), nullable=False),
    sa.Column('patients_tested', sa.Integer(), nullable=True),
    sa.Column('suppression_pct', sa.Numeric(), nullable=True),
    sa.Column('drug_stock_level', sa.Numeric(), nullable=True),
    sa.Column('reporting_delay_days', sa.Integer(), nullable=True),
    sa.Column('quarantine_reason', sa.String(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=True),
    sa.Column('dag_logical_date', sa.Date(), nullable=True),
    sa.Column('quarantined_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('raw_monthly_reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('facility_id', sa.String(), nullable=False),
    sa.Column('report_month', sa.Date(), nullable=False),
    sa.Column('patients_tested', sa.Integer(), nullable=True),
    sa.Column('suppression_pct', sa.Numeric(), nullable=True),
    sa.Column('drug_stock_level', sa.Numeric(), nullable=True),
    sa.Column('reporting_delay_days', sa.Integer(), nullable=True),
    sa.Column('source_file', sa.String(), nullable=True),
    sa.Column('run_id', sa.String(), nullable=True),
    sa.Column('dag_logical_date', sa.Date(), nullable=True),
    sa.Column('ingested_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('monthly_reports',
    sa.Column('facility_id', sa.String(), nullable=False),
    sa.Column('report_month', sa.Date(), nullable=False),
    sa.Column('patients_tested', sa.Integer(), nullable=False),
    sa.Column('suppression_pct', sa.Numeric(), nullable=False),
    sa.Column('drug_stock_level', sa.Numeric(), nullable=False),
    sa.Column('reporting_delay_days', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=True),
    sa.Column('dag_logical_date', sa.Date(), nullable=True),
    sa.Column('ingested_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('drug_stock_level >= 0', name='ck_monthly_reports_stock_nonneg'),
    sa.CheckConstraint('patients_tested >= 0', name='ck_monthly_reports_patients_nonneg'),
    sa.CheckConstraint('reporting_delay_days >= 0', name='ck_monthly_reports_delay_nonneg'),
    sa.CheckConstraint('suppression_pct >= 0 AND suppression_pct <= 100', name='ck_monthly_reports_suppression_range'),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.facility_id'], ),
    sa.PrimaryKeyConstraint('facility_id', 'report_month')
    )
    op.create_table('scored_reports',
    sa.Column('facility_id', sa.String(), nullable=False),
    sa.Column('report_month', sa.Date(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('dag_logical_date', sa.Date(), nullable=True),
    sa.Column('is_anomaly', sa.Boolean(), nullable=False),
    sa.Column('anomaly_score', sa.Numeric(), nullable=False),
    sa.Column('anomaly_reasons', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('forecast_next_quarter_suppression_pct', sa.Numeric(), nullable=True),
    sa.Column('model_version_anomaly', sa.String(), nullable=True),
    sa.Column('model_version_forecast', sa.String(), nullable=True),
    sa.Column('scored_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['facility_id', 'report_month'], ['monthly_reports.facility_id', 'monthly_reports.report_month'], ),
    sa.PrimaryKeyConstraint('facility_id', 'report_month')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scored_reports')
    op.drop_table('monthly_reports')
    op.drop_table('raw_monthly_reports')
    op.drop_table('quarantined_reports')
    op.drop_table('facilities')
    # ### end Alembic commands ###
